name: automerge
on:
  pull_request:
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_DELETE_BRANCH: true
          MERGE_FORKS: true
          MERGE_FILTER_AUTHOR: martadams89
          MERGE_LABELS: ""
