name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: simple-login
          repo: app
          base: master
          head: master
          ignore_fail: true
        continue-on-error: true

      - run: echo "🍏 This job's status is ${{ job.status }}."
