name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          token: ${{ secrets.FORK_PAT }}
          owner: simple-login
          repo: app
          base: master
          head: master
          pr_title: 'sync: from upstream master to ${{ matrix.branch }}'
          pr_message: 'Created by [*${{ github.job }}* workflow job](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) to sync changes from [upstream](${{ github.server_url }}/k8snetworkplumbingwg/${{ github.event.repository.name }}) to [downstream](${{ github.server_url }}/${{ github.repository }}).'
          retries: 1
          retry_after: 3
          auto_approve: true
          auto_merge: true
          merge_method: rebase
          ignore_fail: true
        continue-on-error: true

      - run: echo "🍏 This job's status is ${{ job.status }}."
