name: Sync Fork Master and Auto-merge

on:
  schedule:
    - cron: "*/30 * * * *" # Every 30 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/simple-login/app.git

      - name: Fetch Upstream Master
        run: |
          git fetch upstream master

      - name: Merge Upstream Master into Local Master
        run: |
          git checkout master
          git merge --allow-unrelated-histories upstream/master

      - name: Push Local Master
        run: |
          git push origin master
        env:
          GH_TOKEN: ${{ secrets.FORK_PAT }}

      - name: Create Fork Sync Pull Request
        id: fork_sync_pr
        run: |
          gh pr create --title "sync: from upstream master to ${{ github.ref_name }}" --body "Merged from upstream [simple-login/app](https://github.com/simple-login/app) to [martadams89/sl-app](https://github.com/martadams89/sl-app)." --base master --head ${{ github.actor }}:master
        env:
          GH_TOKEN: ${{ secrets.FORK_PAT }}

      - name: Auto approve Fork Sync PR
        if: steps.fork_sync_pr.outputs.pull-request-url
        run: gh pr review --approve "${{ steps.fork_sync_pr.outputs.pull-request-url }}"
        env:
          GH_TOKEN: ${{ secrets.FORK_PAT }}

      - name: Enable Fork Sync Pull Request Automerge
        if: steps.fork_sync_pr.outputs.pull-request-url
        run: gh pr merge --squash "${{ steps.fork_sync_pr.outputs.pull-request-url }}"
        env:
          GH_TOKEN: ${{ secrets.FORK_PAT }}

      - name: Job Status
        run: echo "🍏 This job's status is ${{ job.status }}."